name: get-mseed-seedlink
description: Downloads and builds libmseed and libslink
runs:
  using: "composite"
  steps:
    - name: Libmseed/Libslink cache setup
      uses: actions/cache@v5
      id: cache-libmseed-libslink
      env:
        cache-name: cache-libmseed-libslink-modules
      with:
        path: |
           ${HOME}/third-party/include/libmseed.h
           ${HOME}/third-party/include/libslink.h
           ${HOME}/third-party/lib/cmake/libmseed/*
           ${HOME}/third-party/lib/libmseed.a
           ${HOME}/third-party/lib/libslink.a

    - if: ${{ steps.cache-libmseed-libslink.outputs.cache-hit != 'true' }}
      name: Build libmseed, libdali, and libslink
      run: |
        mkdir -p ${HOME}/third-party
        wget https://github.com/EarthScope/libmseed/archive/refs/tags/v3.4.0.tar.gz
        tar -xf v3.4.0.tar.gz
        rm v3.4.0.tar.gz
        cd libmseed-3.4.0
        cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang -DBUILD_STATIC_LIBS=ON -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=${HOME}/third-party
        cmake --build build
        cmake --install build
        cd ../
        rm -rf libmseed-3.4.0
        wget https://github.com/EarthScope/libslink/archive/refs/tags/v4.2.0.tar.gz
        tar -xf v4.2.0.tar.gz
        rm v4.2.0.tar.gz
        cd libslink-4.2.0
        CC=clang make
        ls -ltrh ${HOME}/third-party/
        cp libslink.a ${HOME}/third-party/lib/
        cp libslink.h ${HOME}/third-party/include/
        cd ../
        rm -rf libslink-4.2.0

    - name: Copy libslink/libmseed.a
      run: |
        sudo mkdir -p /usr/local/lib/
        sudo mkdir -p /usr/local/include/
        sudo cp -r ${HOME}/third-party/lib/cmake* /usr/local/lib/
        sudo cp ${HOME}/third-party/lib/*.a /usr/local/lib/
        sudo cp ${HOME}/third-party/include/*.h /usr/local/include/
      shell: bash



