name: prepare-environment
description: Prepares the deploy environment
runs:
  using: "composite"
  steps:
    - name: Prepare environment
      run: |
        mkdir -p ${{github.workspace}}/build
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
           tar \
           wget \
           cmake \
           buildah \
           ninja-build \
           clang \
           clang-tidy \
           pkg-config \
           build-essential \
           libtbb-dev
      shell: bash

